import { WORKBENCH_STYLES } from './workbench-styles.js'
import { ORCHESTRATION_STYLES } from './workbench-orchestration-styles.js'
import { MODEL_SETTINGS_HTML, MODEL_STYLES } from './workbench-models-layout.js'

const icon = (paths: string, cls = '') => `<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true">${paths}</svg>`
const search = icon('<circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 4.5 4.5"/>')
const plus = icon('<path d="M12 5v14M5 12h14"/>')
const arrow = icon('<path d="M12 19V5m-6 6 6-6 6 6"/>')
const close = icon('<path d="m6 6 12 12M18 6 6 12"/>')
const brand = icon('<path d="M12 3v5m0 8v5M3 12h5m8 0h5M5.6 5.6l3.5 3.5m5.8 5.8 3.5 3.5M5.6 18.4l3.5-3.5m5.8-5.8 3.5-3.5"/><circle cx="12" cy="12" r="4"/>', 'brand-mark')

/** All task and source content is inserted as text by the bundled browser client. */
export const TASK_WORKBENCH_HTML = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#faf9f6"><title>工单检索</title><link rel="icon" href="data:,"><style>${WORKBENCH_STYLES}${ORCHESTRATION_STYLES}${MODEL_STYLES}</style></head>
<body><a class="skip" href="#main-content">跳到主要内容</a><div class="shell">
<aside class="sidebar" id="sidebar" aria-label="任务导航">
  <div class="sidebar-heading"><a class="brand" href="/retrieval">${brand}<span>工单检索</span></a><button id="close-nav" class="icon-button" aria-label="收起导航">${close}</button></div>
  <a class="new-task" href="/retrieval">${plus}<span>新建检索</span><kbd>Alt N</kbd></a>
  <div class="side-history"><p class="side-label">最近检索</p><nav id="restore" class="history-list" aria-label="最近任务"></nav></div>
  <div class="sidebar-bottom"><button id="model-settings" class="sidebar-settings" type="button">⚙ <span>模型与供应商</span></button><div class="sidebar-foot">${search}<span>从线索，找到答案</span></div></div>
</aside><button id="nav-scrim" class="nav-scrim" aria-label="关闭任务导航" hidden></button>
<main class="main" id="main-content" tabindex="-1">
  <header class="topbar"><div class="row"><button id="open-nav" class="icon-button" aria-controls="sidebar" aria-expanded="false" aria-label="打开任务导航">${icon('<path d="M4 6h16M4 12h16M4 18h16"/>')}</button><span id="breadcrumb">工作空间</span></div><div class="row"><span id="connection" role="status"></span><a class="mobile-brand icon-button" href="/retrieval" aria-label="新建检索">${plus}</a></div></header>
  <div id="error" class="notice error" role="alert" hidden></div>
  <section id="home" class="home">
    <div class="home-intro"><div class="home-symbol">${brand}</div><h1>想找什么工单？</h1><p class="home-lead">说说你的需求，剩下的交给检索。</p></div>
    <form id="query-form" class="query-box">
      <label for="query" class="sr-only">描述需要查找的工单</label>
      <textarea id="query" rows="2" required maxlength="2000" placeholder="例如：查找副卡解绑后仍合账缴费的工单"></textarea>
      <div class="query-footer"><span class="search-mode">${search}工单检索</span><button id="model-selector" class="model-trigger" type="button" aria-haspopup="dialog"><span>选择模型</span>⌄</button><button id="start" class="primary send-button" type="submit" aria-label="开始检索" title="开始检索">${arrow}</button></div>
    </form>
    <div id="examples" class="examples" aria-label="示例检索"><button data-query="查找3条副卡解绑后仍合账缴费或发生扣费争议的工单">${icon('<path d="m10 8 4 8m-6-3-2 1a4 4 0 0 1-4-7l4-2m10 6 2-1a4 4 0 0 1 4 7l-4 2"/>')}<span>解绑后仍合账</span></button><button data-query="查找3条宽带包年到期后转为包月、产生扣费争议的工单">${icon('<path d="M5 3h14v18l-3-2-4 2-4-2-3 2zM9 8h6M9 12h6"/>')}<span>包年到期转包月</span></button></div>
    <section class="recent" id="recent-section" hidden><div class="row between"><h2>继续上次的查找</h2><span class="muted">最近检索</span></div><nav id="recent" class="history-list" aria-label="继续之前的检索"></nav></section>
  </section>
  <section id="task" class="task" hidden>
    <div class="task-head"><div class="task-heading"><h1 id="query-title" tabindex="-1">正在打开检索…</h1><details class="scope"><summary>检索范围</summary><div id="scope-content"></div></details></div><div class="task-status"><span class="status-dot" aria-hidden="true"></span><p id="status" role="status"></p><small id="counts"></small></div></div>
    <section id="live-work" class="live-work" aria-label="实时检索进度"><div class="live-heading"><span class="ai-orbit" aria-hidden="true">${brand}</span><div class="live-copy"><span class="eyebrow">检索助手</span><p id="live-title" role="status">正在准备检索</p></div><time id="elapsed"></time><button id="show-activity" class="icon-button" aria-label="查看完整检索过程">${icon('<path d="m9 5 7 7-7 7"/>')}</button></div><ol id="stage-rail" class="stage-rail" aria-label="检索阶段"></ol><p id="live-note" class="live-note" hidden></p><div id="live-metrics" class="live-metrics"></div></section>
    <div class="task-toolbar"><nav class="tabs" role="tablist" aria-label="任务视图"><button id="tab-results" role="tab" aria-selected="true" aria-controls="results-view">工单结果</button><button id="tab-process" role="tab" aria-selected="false" aria-controls="process-view" tabindex="-1">检索过程</button><button id="tab-collaboration" role="tab" aria-selected="false" aria-controls="collaboration-view" tabindex="-1">专家与知识</button><button id="tab-report" role="tab" aria-selected="false" aria-controls="report-view" tabindex="-1">检索报告</button></nav><button id="delivery-link" class="download-trigger" aria-haspopup="dialog">${icon('<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>')}<span>下载</span></button></div>
    <div id="workspace" class="workspace" data-detail="false"><div class="primary-pane">
      <section id="results-view" role="tabpanel" aria-labelledby="tab-results"><div class="row between list-heading"><h2>已确认工单 <span id="confirmed-count" class="count">0</span></h2></div><div id="early-progress" class="empty" hidden></div><details id="result-summary" class="result-summary" hidden><summary>检索结论与范围</summary><p id="result-explanation"></p><p id="result-boundary" class="muted"></p></details></section>
      <section id="process-view" role="tabpanel" aria-labelledby="tab-process" hidden><div class="section-heading"><h2>正在发生</h2><span id="activity-caption" class="muted"></span></div><div id="activity-log" class="activity-log" role="log" aria-label="检索活动" aria-live="polite" aria-relevant="additions"></div><details class="process-block"><summary>搜索详情</summary><div id="process-search"></div><p id="channels" class="muted"></p></details><details id="expert-panel" class="process-block" hidden><summary>专项核查</summary><div id="experts"></div></details><details class="process-block"><summary>补充与回复</summary><div id="timeline"></div></details><details id="feedback-panel" class="process-block" hidden><summary>反馈记录</summary><div id="feedback-history"></div></details><details id="candidate-disclosure" class="process-block"><summary>检索线索</summary><label for="candidate-view" class="sr-only">查看范围</label><select id="candidate-view"><option value="current">当前线索</option><option value="history">历史线索</option></select><div id="process-list-slot"></div></details></section>
      <section id="collaboration-view" role="tabpanel" aria-labelledby="tab-collaboration" hidden><div class="section-heading"><div><span class="eyebrow">协作空间</span><h2>各有所长，一起找到答案</h2></div><span id="team-count" class="muted"></span></div><div class="orchestration-map"><div id="coordinator-node" class="coordinator-node"><span class="node-icon">${brand}</span><div><strong>主检索 Agent</strong><small id="coordinator-state">理解需求 · 分派核查</small></div></div><div id="expert-lanes" class="expert-lanes"></div><div id="synthesis-node" class="synthesis-node"><span aria-hidden="true">✓</span><div><strong>汇总与证据核对</strong><small id="synthesis-state">确认符合要求的工单</small></div></div></div><div class="section-heading library-heading"><div><span class="eyebrow">领域知识</span><h2>专家的知识库</h2></div><span id="knowledge-count" class="muted"></span></div><div class="library-toolbar"><label for="knowledge-search" class="sr-only">搜索知识条目</label><input id="knowledge-search" type="search" placeholder="搜索知识、业务或关键词…"><button id="knowledge-retry" class="link" hidden>重新加载</button></div><div id="domain-filters" class="domain-filters" role="group" aria-label="知识领域"></div><div id="knowledge-list" class="knowledge-list"></div></section>
      <div id="list-region"><p id="candidate-note" class="muted"></p><button id="new-results" class="secondary" hidden>有新结果，点击更新</button><div id="cards" tabindex="0" aria-label="工单列表"></div><nav class="row pagination" aria-label="工单分页"><button id="prev-page" disabled>上一页</button><span id="page-status" role="status"></span><button id="next-page" disabled>下一页</button></nav></div>
      <section id="report-view" class="report" role="tabpanel" aria-labelledby="tab-report" hidden><div class="report-heading"><h2>检索报告</h2><div class="report-tools row"><label for="audience" class="sr-only">报告用途</label><select id="audience"><option value="operator">工作查阅</option><option value="handoff">汇报交接</option></select><button id="save-report" class="primary" disabled>生成报告</button><button id="reload-report" class="icon-button" aria-label="刷新报告" title="刷新报告">${icon('<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-1l2 6M4 12l2 6a7 7 0 0 0 12-1"/>')}</button></div></div><div id="report-error" class="notice error" role="alert" hidden></div><div id="report-generating" class="report-generating" role="status" hidden><p class="shimmer-text">正在结合工单依据撰写报告…</p><div class="skeleton-line"></div><div class="skeleton-line"></div><div class="skeleton-line"></div></div><div id="report-content"></div></section>
    </div></div>
    <section id="input-panel" class="composer"><div id="question" class="notice" hidden></div><div id="question-options" class="row"></div><form id="supplement-form"><label for="supplement" id="supplement-label" class="sr-only">补充检索要求</label><textarea id="supplement" rows="1" required maxlength="2000" placeholder="继续补充，或调整查找范围…"></textarea><button id="send-supplement" type="submit" class="primary send-button" aria-label="发送补充" title="发送补充">${arrow}</button></form><div class="composer-meta"><button id="model-selector-task" class="model-trigger" type="button" aria-haspopup="dialog"><span>选择模型</span>⌄</button><button id="context-meter" class="context-meter" type="button" aria-label="上下文用量待测量"><svg viewBox="0 0 24 24" aria-hidden="true"><circle class="context-track" cx="12" cy="12" r="9"/><circle id="context-fill" class="context-fill" cx="12" cy="12" r="9" stroke-dasharray="0 57"/></svg><span id="context-label">待测量</span></button><button id="output-usage" class="model-trigger" type="button" aria-haspopup="dialog">输出待计量</button><p id="receipt" role="status" class="muted"></p><small id="input-hint"></small><button id="cancel" class="link" type="button">停止检索</button></div></section>
  </section>
</main></div><div id="history-notice" class="history-notice" role="status" hidden></div>
<dialog id="evidence-panel" class="evidence" aria-labelledby="detail-title" hidden><div class="evidence-head"><div><span class="eyebrow">工单原文</span><strong id="detail-title" tabindex="-1">查看依据</strong></div><button id="close-detail" class="icon-button" aria-label="关闭证据，返回阅读" title="关闭">${close}</button></div><div id="detail" aria-live="polite"></div></dialog>
<dialog id="knowledge-dialog" class="evidence knowledge-dialog" aria-labelledby="knowledge-title"><div class="evidence-head"><div><span class="eyebrow">领域知识</span><strong id="knowledge-title" tabindex="-1">知识条目</strong></div><button id="close-knowledge" class="icon-button" aria-label="关闭知识条目">${close}</button></div><div id="knowledge-body" class="knowledge-body"></div></dialog>
<dialog id="delivery" class="delivery" aria-labelledby="delivery-title"><div class="row between"><h2 id="delivery-title">下载工单</h2><button id="close-delivery" class="icon-button" aria-label="关闭下载">${close}</button></div><p id="delivery-note" class="muted"></p><div id="delivery-error" class="notice error" role="alert" hidden></div><div class="delivery-controls"><label for="template">文件内容</label><select id="template"><option value="summary">工单概览与依据</option><option value="full">工单与完整正文</option></select><div class="row"><button id="download" class="primary" disabled>生成 CSV</button><button id="download-jsonl" disabled>生成 JSONL</button></div></div><p id="delivery-state" class="toolbar-note"></p><p id="download-receipt" role="status"></p><div id="artifacts"></div></dialog>
<dialog id="feedback-dialog" aria-labelledby="feedback-title"><form id="feedback-form"><div id="feedback-error" class="notice error" role="alert" hidden></div><h2 id="feedback-title">反馈问题</h2><label for="feedback-relevance">这条工单符合要求吗？</label><select id="feedback-relevance"><option value="unrelated">不相关</option><option value="related">相关</option></select><label for="feedback-text">补充原因 <span class="muted">选填</span></label><textarea id="feedback-text" maxlength="1500" placeholder="指出问题，有助于我们重新核实"></textarea><div class="dialog-actions row"><button id="send-feedback" class="primary" type="submit">发送反馈</button><button id="close-feedback" type="button">取消</button></div></form></dialog>
${MODEL_SETTINGS_HTML}<script type="module" src="/retrieval/workbench-client.js"></script></body></html>`
