export const MODEL_SETTINGS_HTML = String.raw`<dialog id="context-dialog" class="model-dialog" aria-labelledby="context-title"><div class="row between"><h2 id="context-title">上下文使用</h2><button id="context-close" class="icon-button" aria-label="关闭上下文详情">✕</button></div><p id="context-description" style="white-space:pre-line"></p><small class="muted">显示主 Agent 最近一次完整模型请求的输入用量；专家各自管理独立上下文。累计 token 消耗不代表当前窗口占用。</small></dialog><dialog id="usage-dialog" class="model-dialog" aria-labelledby="usage-title"><div class="row between"><h2 id="usage-title">输出 token 消耗</h2><button id="usage-close" class="icon-button" aria-label="关闭输出用量详情">✕</button></div><p id="usage-description" style="white-space:pre-line"></p><small class="muted">按供应商回执累计主 Agent 与所有专家的输出，包含此前轮次和失败调用；输入与缓存 token 不计入。报告生成、Wiki 后台作业另计。</small></dialog><dialog id="model-dialog" class="model-dialog" aria-labelledby="model-title">
<div class="row between"><h2 id="model-title">模型与供应商</h2><button id="model-close" class="icon-button" aria-label="关闭模型设置">✕</button></div>
<p id="model-scope" class="muted"></p><p id="model-error" class="notice error" role="alert" hidden></p>
<section id="model-picker-view"><label for="model-search" class="sr-only">搜索模型</label><input id="model-search" type="search" placeholder="搜索模型…"><div id="model-reasoning-row" class="model-reasoning" hidden><label for="model-reasoning">当前模型的推理强度</label><select id="model-reasoning"></select></div><div id="model-options" role="listbox" aria-label="可用模型"></div><button id="manage-models" class="model-manage" type="button">＋ 添加或管理供应商 <span>API、本地模型与更多服务 →</span></button></section>
<section id="model-settings-view" hidden><button id="models-back" class="link" type="button">← 返回模型列表</button><form id="model-config-form" class="model-form">
<label for="provider-choice">供应商</label><select id="provider-choice"></select><label for="provider-id">供应商标识</label><input id="provider-id" required placeholder="例如 company-gateway">
<label for="provider-api">API 协议</label><select id="provider-api"></select><label for="provider-url">API 地址</label><input id="provider-url" type="url" placeholder="使用供应商默认地址，或填写 https://…/v1">
<p id="model-local-note" class="muted" hidden>容器访问本机 Ollama 请使用 host.docker.internal:11434/v1。按实际加载参数填写上下文容量。</p>
<label for="provider-key">API 密钥</label><input id="provider-key" type="password" autocomplete="new-password" placeholder="本地无鉴权服务可以留空">
<div class="row between"><label for="provider-model">模型 ID</label><button id="model-discover" class="link" type="button">获取模型列表</button></div><input id="provider-model" list="provider-model-list" required placeholder="输入供应商提供的模型 ID"><datalist id="provider-model-list"></datalist><small id="model-discovery-status" role="status" class="muted"></small>
<div class="model-capacities"><div><label for="provider-context">上下文窗口 · tokens</label><input id="provider-context" type="number" min="1024" max="10000000" placeholder="使用供应商目录值"></div><div><label for="provider-output">最大输出 · tokens</label><input id="provider-output" type="number" min="1024" max="10000000" placeholder="使用供应商目录值"></div></div>
<p class="muted">密钥只存于本机服务端。OpenCode Go 的会话标识由系统自动附加。</p><button id="model-save" class="primary" type="submit">保存并使用</button></form></section></dialog>`

export const MODEL_STYLES = String.raw`
.model-trigger { display:inline-flex; align-items:center; gap:7px; border:0; background:transparent; padding:6px 9px; color:#63746c; border-radius:8px; font-size:12px; max-width:260px; }
.model-trigger span { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.model-trigger:hover { background:#eaf0e9; color:#245d50; }
.model-dialog { width:min(560px,calc(100vw - 30px)); max-height:85dvh; padding:26px; border:1px solid #dce4dc; border-radius:20px; box-shadow:0 25px 90px #18382a25; }
.model-dialog::backdrop { background:#132b2340; backdrop-filter:blur(4px); }.model-dialog h2 { margin:0; font-size:20px; }.model-dialog p { line-height:1.7; }
.model-dialog input,.model-dialog select { width:100%; padding:11px 12px; border:1px solid #d7dfd8; border-radius:9px; background:#fff; color:#24382e; font:inherit; box-sizing:border-box; }
#model-options { max-height:45dvh; overflow:auto; padding:8px 0; }.model-group { color:#849187; font-size:11px; margin:15px 10px 5px; }
.model-option { width:100%; display:flex; align-items:center; justify-content:space-between; border:0; text-align:left; background:transparent; padding:13px 12px; border-radius:10px; transition:background .18s; }
.model-option strong,.model-option small { display:block; }.model-option strong { font-size:14px; font-weight:500; }.model-option small { color:#8b958e; margin-top:3px; font-size:11px; }
.model-option:hover,.model-option[aria-selected=true] { background:#edf4ee; }.model-option[aria-selected=true]>span { color:#297462; }
.model-reasoning { display:flex; align-items:center; justify-content:space-between; gap:14px; margin:14px 0 3px; font-size:12px; color:#65766d; }.model-reasoning select { width:auto; max-width:65%; padding:7px; }
.model-manage { display:block; width:100%; text-align:left; padding:17px 10px 4px; border:0; border-top:1px solid #e3e8e1; background:transparent; color:#366454; }.model-manage span { display:block; margin-top:5px; color:#8b958e; font-size:11px; }
.model-form { display:grid; gap:8px; padding-top:14px; }.model-form label { font-size:12px; color:#65766d; }.model-form p { margin:3px 0 8px; font-size:12px; }.model-form>label:not(:first-child) { margin-top:7px; }
.model-capacities { display:grid; grid-template-columns:1fr 1fr; gap:12px; margin-top:7px; }.model-capacities input { margin-top:6px; }.model-form .primary { padding:12px; margin-top:8px; }
.sidebar-settings { display:flex; align-items:center; gap:9px; width:100%; border:0; border-radius:8px; background:transparent; padding:12px; color:#78877d; text-align:left; }.sidebar-settings:hover { background:#e9eee6; }
.context-meter { display:flex; align-items:center; gap:7px; border:0; background:transparent; color:#76877c; font:11px/1.4 inherit; padding:4px 6px; border-radius:8px; cursor:help; }.context-meter svg { width:24px; height:24px; transform:rotate(-90deg); }.context-meter circle { fill:none; stroke-width:2.8; }.context-track { stroke:#dfe6dc; }.context-fill { stroke:#568e76; transition:stroke-dasharray .6s ease,stroke .3s; }.context-meter[data-pressure=high] .context-fill { stroke:#bb8740; }.context-meter:hover { background:#edf1e8; }
@media(prefers-reduced-motion:reduce) { .context-fill,.model-option { transition:none; } }
`
